"""extends asset type enum

Revision ID: 22eb674867a8
Revises:
Create Date: 2025-09-04 00:22:49.071700

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "22eb674867a8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
