"""Initial migration

Revision ID: 426497007c5e
Revises: 
Create Date: 2025-09-07 00:19:12.189293

"""


# revision identifiers, used by Alembic.
revision = '426497007c5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
