"""Add user_id to assets table

Revision ID: 9a24d533141c
Revises: 426497007c5e
Create Date: 2025-09-07 22:39:27.692668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a24d533141c'
down_revision = '426497007c5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
