"""Add user_id field to assets table

Revision ID: a0afe386843f
Revises: 9a24d533141c
Create Date: 2025-09-07 22:40:07.773196

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0afe386843f"
down_revision = "9a24d533141c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column("assets", sa.Column("user_id", sa.Integer(), nullable=True))

    # Get the first user ID to assign to existing assets
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM users LIMIT 1"))
    first_user_id = result.fetchone()

    if first_user_id:
        # Update existing assets with the first user ID
        op.execute(
            f"UPDATE assets SET user_id = {first_user_id[0]} WHERE user_id IS NULL"
        )

    # Now make the column not null
    op.alter_column("assets", "user_id", nullable=False)

    # Drop the old unique index on symbol
    op.drop_index("ix_assets_symbol", table_name="assets")

    # Create new indexes
    op.create_index(op.f("ix_assets_symbol"), "assets", ["symbol"], unique=False)
    op.create_index("idx_assets_user_id", "assets", ["user_id"], unique=False)
    op.create_index(
        "idx_assets_user_symbol", "assets", ["user_id", "symbol"], unique=True
    )
    op.create_foreign_key(
        None, "assets", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "assets", type_="foreignkey")
    op.drop_index("idx_assets_user_symbol", table_name="assets")
    op.drop_index("idx_assets_user_id", table_name="assets")
    op.drop_index(op.f("ix_assets_symbol"), table_name="assets")
    op.create_index("ix_assets_symbol", "assets", ["symbol"], unique=True)
    op.drop_column("assets", "user_id")
    # ### end Alembic commands ###
