"""adds today pnl field to asset

Revision ID: a131a7505660
Revises: a7147b28ca25
Create Date: 2025-09-26 23:47:45.801681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a131a7505660'
down_revision = 'a7147b28ca25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_assets', sa.Column('today_pnl', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('portfolio_assets', sa.Column('today_pnl_percent', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_assets', 'today_pnl_percent')
    op.drop_column('portfolio_assets', 'today_pnl')
    # ### end Alembic commands ###
