"""add_analysis_configuration_table

Revision ID: a7147b28ca25
Revises: a94c0f4e7c77
Create Date: 2025-09-20 10:18:19.682226

"""


# revision identifiers, used by Alembic.
revision = 'a7147b28ca25'
down_revision = 'a94c0f4e7c77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
