"""add_realized_pnl_fields_to_portfolio_assets

Revision ID: a94c0f4e7c77
Revises: f1b2d5154794
Create Date: 2025-09-16 10:25:00.318436

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'a94c0f4e7c77'
down_revision = 'f1b2d5154794'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_assets', sa.Column('realized_pnl', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('portfolio_assets', sa.Column('realized_pnl_percent', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_assets', 'realized_pnl_percent')
    op.drop_column('portfolio_assets', 'realized_pnl')
    # ### end Alembic commands ###
